# Stage 1 - install dependencies
FROM node:20-alpine AS dependencies
LABEL key="dependencies"
WORKDIR /app
COPY package*.json ./
RUN npm install

# Stage 2 - build the app for dev mode
FROM dependencies AS dev
LABEL key="dev"
COPY . .
CMD ["npm", "run", "dev", "--", "--host"]

# Stage 3 - build the app for production
#FROM dependencies AS build
#LABEL key="build"
#COPY . .
#RUN npm run build

# Stage 4 - serve the production build
#FROM nginx:alpine AS prod
#LABEL key="prod"
## Remove default Nginx website
#RUN rm -rf /usr/share/nginx/html/*
## Copy built frontend files from the build stage
#WORKDIR /app
#COPY --from=build /app/build /usr/share/nginx/html
#COPY nginx.conf /etc/nginx/conf.d/default.conf
## Run the production build
#CMD ["nginx", "-g", "daemon off;"]